name: Build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "boards/**"
      - "cmake/**"
      - "drivers/**"
      - "dts/**"
      - "include/**"
      - "src/**"
      - "tests/**"
      - "*"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "boards/**"
      - "cmake/**"
      - "drivers/**"
      - "dts/**"
      - "include/**"
      - "src/**"
      - "tests/**"
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/innovaker/zmk-build-arm:2.4
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    strategy:
      matrix:
        board: [proton_c, nice_nano, bluemicro840_v1, nrfmicro_13]
        shield:
          - boardsource3x4
          - corne_left
          - corne_right
          - kyria_left
          - kyria_right
          - lily58_left
          - lily58_right
          - iris_left
          - iris_right
          - jorne_left
          - jorne_right
          - jian_left
          - jian_right
          - reviung41
          - romac
          - romac_plus
          - settings_reset
          - quefrency_left
          - quefrency_right
          - nibble
        include:
          - board: proton_c
            shield: clueboard_california
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: zmk
        timeout-minutes: 1
      - name: Cache modules
        uses: actions/cache@v2
        env:
          cache-name: modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: 3-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/west.yml') }}
          restore-keys: |
            3-${{ runner.os }}-build-${{ env.cache-name }}-
            3-${{ runner.os }}-build-
            3-${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: West init
        run: west init -l zmk
      - name: West update
        run: west update
        timeout-minutes: 3
      - name: West build
        run: west build -s zmk/tests -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}
      - name: Archive build
        uses: actions/upload-artifact@v2
        if: ${{ matrix.board != 'proton_c' }}
        with:
          name: "${{ matrix.board }}-${{ matrix.shield }}-zmk-uf2"
          path: build/zephyr/zmk.uf2
