name: Tests

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "tests/**"
      - "src/**"
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "tests/**"
      - "src/**"

jobs:
  integration_test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/innovaker/zmk-build-arm:2.4
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: zmk
      - name: Cache modules
        uses: actions/cache@v2
        env:
          cache-name: modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: 3-${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/west.yml') }}
          restore-keys: |
            3-${{ runner.os }}-build-${{ env.cache-name }}-
            3-${{ runner.os }}-build-
            3-${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true
      - name: West init
        run: west init -l zmk
      - name: West update
        run: west update
        timeout-minutes: 3
      - name: Test all
        run: west test
      - name: Archive build
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: "log-files"
          path: zmk/build/**/*.log
